config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :volunteer_assignments
  resources :volunteers
  resources :admins
  resources :events do
    post :volunteer, on: :member
    delete :unvolunteer, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/my_events", to: "volunteers#my_events", as: :my_events

  resources :sessions, only: [ :new, :create, :destroy ]
  get "signup", to: "volunteers#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  post "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
    # Associations
    has_secure_password
    attr_readonly :username
    has_many :volunteer_assignments, dependent: :destroy
    has_many :events, through: :volunteer_assignments

    # Validations
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, presence: true, on: [ :create ], length: { minimum: 6 }
    validates :full_name, presence: true
    validates :phone_number, format: { with: /\A(\+1\s?)?(\(\d{3}\)|\d{3})[ \-\.]?\d{3}[ \-\.]?\d{4}\z/,
        message: "must be a valid US phone number" }, allow_blank: true

    # Calculation of Total Volunteer Hours
    def total_hours
        volunteer_assignments.completed.sum(:hours)
    end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: %i[ show edit update destroy ]
  before_action :admin_access_only, only: %i[ index ]
  before_action :user_or_admin_access_only, only: %i[ show edit update destroy ]
  before_action :require_volunteer_login, only: [:my_events]

  

  # GET /volunteers or /volunteers.json
  def index
    @volunteers = Volunteer.all
    render layout: 'admins'
  end

  # GET /volunteers/1 or /volunteers/1.json
  def show
    if is_admin?
      render layout: 'admins'
    end
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
    if is_admin?
      render layout: 'admins'
    end
  end

  # GET /volunteers/1/edit
  def edit
    if is_admin?
      render layout: 'admins'
    end
  end

  # POST /volunteers or /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        session[:user_id] = @volunteer.id
        format.html { redirect_to @volunteer, notice: "Volunteer was successfully created." }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1 or /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: "Volunteer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1 or /volunteers/1.json
  def destroy
    @volunteer.destroy!

    respond_to do |format|
      format.html {
        if is_admin?
          redirect_to volunteers_path, notice: "Volunteer was successfully destroyed.", status: :see_other
        else
          reset_session
          redirect_to root_path, notice: "Your account has been deleted"
        end
      }
      format.json { head :no_content }
    end
  end


  def my_events
    unless @volunteer
      redirect_to login_path, alert: "You must be logged in."
      return
    end
    @pending_assignments   = @volunteer.volunteer_assignments.where(status: "pending").includes(:event)
    @approved_assignments  = @volunteer.volunteer_assignments.where(status: "approved").includes(:event)
    @completed_assignments = @volunteer.volunteer_assignments.where(status: "completed").includes(:event)
    @cancelled_assignments = @volunteer.volunteer_assignments.where(status: "cancelled").includes(:event)

    @total_hours = @completed_assignments.sum(:hours_worked)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      begin
        @volunteer = Volunteer.find(params.expect(:id))
      rescue
        if is_admin?
          redirect_to volunteers_path, alert: 'That volunteer could not be found.'
        else # this should never get hit except in a race condition where admin deletes a user and the user accesses their profile
          redirect_to root_path, alert: 'Access Denied'
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def volunteer_params
      permitted = [
        :full_name,
        :email,
        :address,
        :phone_number,
        :skills_interests,
      ]

      permitted << :username if action_name == "create"
      if action_name == 'create' || (action_name == 'update' && params[:volunteer][:password].present?)
        permitted << :password
        permitted << :password_confirmation
      end

      params.require(:volunteer).permit(permitted)
    end

    # Sets restricted access to current user of their own data or admin
    def user_or_admin_access_only
      redirect = false
      if is_admin?.eql?(false)
        if session[:user_id].nil?
          redirect = true
        elsif session[:user_id].eql?(@volunteer.id).eql?(false)
          redirect = true
        end
      end
      if redirect
        redirect_to root_url, alert: "You are not authorized to access that."
      end
    end

    def require_volunteer_login
      redirect_to login_path unless session[:user_id]
    end

end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_events_table.html.erb
<% if assignments.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Event</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">Hours Logged</th>
      </tr>
    </thead>

    <tbody>
      <% link_classes = 'link-dark link-underline-opacity-0 link-underline-opacity-75-hover' %>

      <% assignments.each do |assignment| %>
        <tr>
          <!-- LEFT COLUMN WITH VIEW LINK -->
          <td class="col-2">
            <%= link_to event_path(assignment.event), class: link_classes do %>
              <i class="bi bi-eye-fill"></i> View Event
            <% end %>
          </td>

          <td><%= link_to assignment.event.title, assignment.event , class: link_classes %></td>
          <td class="col-2"><%= assignment.event.event_date %></td>

          <td class="col-2">
            <span class="badge bg-<%= 
              case assignment.status
              when "pending" then "warning"
              when "approved" then "primary"
              when "completed" then "success"
              when "cancelled" then "danger"
              else "secondary"
              end
            %>">
              <%= assignment.status.capitalize %>
            </span>
          </td>

          <td class="col-2"><%= assignment.hours_worked || "-" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No events in this category.</p>
<% end %>

app/views/volunteers/_form.html.erb
<div class="container-fluid justify-content-start">
    <div class="col-sm-4 col-12 ">
        <%= form_with(model: volunteer) do |form| %>
            <% if volunteer.errors.any? %>
                <div style="color: red">
                    <h2><%= pluralize(volunteer.errors.count, "error") %> prohibited this volunteer from being
                        saved:</h2>

                    <ul>
                        <% volunteer.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <p class="text-muted">
                <span class="text-danger">*</span> indicates fields are required
            </p>

            <div class="row my-3">
                <div class="col-md-6 col-12">
                    <%= required_label(form, :username) %>
                    <%= form.text_field :username,
                      class: "form-control",
                      disabled: !@volunteer.new_record?,
                      required: @volunteer.new_record? %>
                </div>

                <div class="col-md-6 col-12">
                    <%= required_label(form, :full_name, "Full Name") %>
                    <%= form.text_field :full_name, class: 'form-control', required: true %>
                </div>
            </div>

            <div class="my-3 row">
                <div class="col-md-6 col-12">
                    <%= required_label(form, :email) %>
                    <%= form.email_field :email, class: 'form-control', required: true %>
                </div>

                <div class="col-md-6 col-12">
                    <%= form.label :phone_number, class: 'form-label' %>
                    <%= form.telephone_field :phone_number, class: 'form-control' %>
                </div>
            </div>

            <div class="my-3 row">
                <div class="col">
                    <%= form.label :address, class: 'form-label' %>
                    <%= form.text_field :address, class: 'form-control' %>
                </div>
            </div>
            <div class="my-3 row">
                <div class="col">
                    <%= form.label :skills_interests, class: 'form-label' %>
                    <%= form.textarea :skills_interests, class: 'form-control' %>
                </div>
            </div>

            <div class="my-3 row">
                <% if request.path.ends_with? '/edit' %>
                <div class="text-danger">
                    Only enter the password fields if you are wanting to update the password
                </div>
                <% end %>
                <div class="col-md-6 col-12">
                    <%= required_label(form, :password) %>
                    <%= form.password_field :password, class: 'form-control', required: @volunteer.new_record? %>
                </div>

                <div class="col-md-6 col-12">
                    <%= required_label(form, :password_confirmation, "Confirm Password") %>
                    <%= form.password_field :password_confirmation, class: 'form-control', required: @volunteer.new_record? %>
                </div>
            </div>

            <div class="my-3 row">
                <div class="col">
                <%= form.submit class: 'btn btn-primary col-5' %>
                <%= link_to 'Cancel', (@volunteer.id ? volunteer_path(@volunteer) : volunteers_path), class: 'btn btn-danger col-5' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/volunteers/_volunteer.html.erb
<div id="<%= dom_id volunteer %>" class="col-md-6 col-12">
  <div>
    <strong>Username:</strong>
    <%= volunteer.username %>
  </div>

  <div>
    <strong>Full name:</strong>
    <%= volunteer.full_name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= volunteer.email %>
  </div>

  <div>
    <strong>Phone number:</strong>
    <%= volunteer.phone_number %>
  </div>

  <div>
    <strong>Address:</strong>
    <%= volunteer.address %>
  </div>

  <div>
    <strong>Skills interests:</strong>
    <%= volunteer.skills_interests %>
  </div>

</div>

app/views/volunteers/_volunteer_list.html.erb
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col">Username</th>
        <th scope="col">Full Name</th>
        <th scope="col">Skills & Interests</th>
    </tr>
    </thead>
    <tbody>
    <% link_classes='link-dark link-underline-opacity-0 link-underline-opacity-75-hover' %>
    <% if @volunteers.nil? || @volunteers.length.eql?(0) %>
        <tr id="<%= dom_id volunteer %>" scope="row">
            <td colspan="4" class="text-danger">No Volunteers Found</td>
        </tr>
    <% else %>
        <% @volunteers.each do |volunteer| %>
        <tr id="<%= dom_id volunteer %>" scope="row">
            <td class="col-1">
                <%= link_to volunteer, class: link_classes do %>
                    <i class="bi bi-eye-fill"></i> View Profile
                <% end %>
                <br />
                <%= link_to volunteer_assignments_path + "?user_id=#{volunteer.id}", class: link_classes do %>
                    <i class="bi bi-intersect"></i> Assignments
                <% end %>
                <br />
                <%= link_to volunteer, class: link_classes, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                    <i class="bi bi-trash2-fill"></i> Delete User
                <% end %>
            </td>

            <td class="col-2"><%= volunteer.username %></td>
            <td class="col-3">
                <%= volunteer.full_name %>
            </td>

            <td class="col">
                <%= volunteer.skills_interests %>
            </td>
        </tr>
        <% end %>
    <% end %>
    </tbody>
</table>

app/views/volunteers/edit.html.erb
<% content_for :title, "Editing: #{@volunteer.username}" -%>

<%= render "form", volunteer: @volunteer %>

app/views/volunteers/index.html.erb
<% content_for :title, "Volunteers" %>

<div id="volunteers" class="col-12 justify-content-left">
    <%= link_to new_volunteer_path, class: 'btn btn-primary' do %>
        <i class="bi bi-plus-circle-fill"></i> New Volunteer
    <% end %>
    <%= render partial: 'volunteers/volunteer_list' %>
</div>

app/views/volunteers/my_events.html.erb
<h3>My Events</h3>

<div class="alert alert-info">
  <strong>Total Hours Volunteered:</strong>
  <%= @total_hours || 0 %> hours
</div>

<hr>

<h4>Pending</h4>
<%= render partial: "events_table", locals: { assignments: @pending_assignments } %>

<hr>

<h4>Approved</h4>
<%= render partial: "events_table", locals: { assignments: @approved_assignments } %>

<hr>

<h4>Completed</h4>
<%= render partial: "events_table", locals: { assignments: @completed_assignments } %>

<hr>

<h4>Cancelled</h4>
<%= render partial: "events_table", locals: { assignments: @cancelled_assignments } %>

app/views/volunteers/new.html.erb
<h3>Volunteer Registration</h3>
<%= render "form", volunteer: @volunteer %>

app/views/volunteers/show.html.erb
<% content_for :title, "Volunteer #{@volunteer.id}: #{@volunteer.username}" -%>

<div>
    <%= link_to "Edit", edit_volunteer_path(@volunteer), class: 'btn btn-primary' %>
</div>

<%= render @volunteer %>

<%
    # this creates a form that submits to the method delete
%>
<%= button_to "Delete Account",
  @volunteer,
  method: :delete,
  class: 'btn btn-danger',
  form: { data: {
      turbo_confirm: 'Are you sure?'
  } }
%>