config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :volunteer_assignments
  resources :volunteers
  resources :admins
  resources :events do
    post :volunteer, on: :member
    delete :unvolunteer, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/my_events", to: "volunteers#my_events", as: :my_events

  resources :sessions, only: [ :new, :create, :destroy ]
  get "signup", to: "volunteers#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  post "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/views/admins/components/_navigation.html.erb
<header class="px-3 py-2 text-bg-dark border-bottom">
    <% navbarName='navbarAdmin' %>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid justify-content-lg-start">
            <button class="navbar-toggler navbar-dark btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#<%= navbarName %>" aria-controls="<%= navbarName %>" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="<%= navbarName %>">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li>
                        <%= link_to admins_path, class: "nav-link", 'aria-current' => 'page' do %>
                            <i class="bi bi-house-fill"></i> Home
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <%= link_to volunteers_path, class: "nav-link", 'aria-current' => 'page' do %>
                            <i class="bi bi-people-fill"></i> Volunteers
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <%= link_to events_path, class: "nav-link", 'aria-current' => 'page' do %>
                            <i class="bi bi-calendar-event-fill"></i> Events
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <%= link_to volunteer_assignments_path, class: "nav-link", 'aria-current' => 'page' do %>
                            <i class="bi bi-intersect"></i> Volunteer Assignments
                        <% end %>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <%= link_to "#{@admin.name.titleize}", '#', class: "nav-link dropdown-toggle", 'data-bs-toggle' => "dropdown", 'aria-expanded' => "false" %>
                        <ul class="dropdown-menu dropdown-menu-end text-small">
                            <li>
                                <%= link_to @admin, class: "dropdown-item" do %>
                                    <i class="bi bi-person-circle"></i> Profile
                                <% end %>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <%= link_to logout_path, class: "dropdown-item" do %>
                                    Sign out
                                <% end %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>